### ISSUE TITLE
Unable to git clone Waifu2x

### ISSUE THREAD

**Issue by WindyGhost** [CyFeng16/MVIMP#22]
Yesterday i tried Waifu2x on colab notebook and it worked , but today when i tried i got a fatal error .

> fatal: Remote branch waifu2x-ncnn-vulkan not found in upstream origin

Can you fix it please .

**Comment by CyFeng16** [comment]
Oops, this is a historical issue, and the test code has not been completely removed. Corrections have been made. (#23 )

**Comment by WindyGhost** [comment]
So is it fixed now ?

**Comment by CyFeng16** [comment]
I think so. Take a try plz.

**Comment by WindyGhost** [comment]
Ok

**Comment by WindyGhost** [comment]
No it's not fixed

**Comment by WindyGhost** [comment]
I used this command

> !git clone -b waifu2x-ncnn-vulkan https://github.com/CyFeng16/MVIMP.git

Is it by any chance that you made changes to this command ?

**Comment by re2cc** [comment]
> I used this command
> 
> > !git clone -b waifu2x-ncnn-vulkan https://github.com/CyFeng16/MVIMP.git
> 
> Is it by any chance that you made changes to this command ?

Use:
`git clone https://github.com/CyFeng16/MVIMP.git`

~~I think something similar happened to me once... But it was just a mistake to download a part of DeOldfy, and it worked.
You only get that one error?~~

**Comment by CyFeng16** [comment]
Two things:
- We had deleted merged branch so we correct it to `git clone https://github.com/CyFeng16/MVIMP.git` in #23 
- We leave a typo in `README.md` thus link to a wrong filename, it was fixed in #25 

Thanks for pointing out. Take ur chance and try once again :)

**Comment by WindyGhost** [comment]
Thanks .
It worked .
