### ISSUE TITLE
Possibly unnecessary compilation of waifu2x

### ISSUE THREAD

**Issue by re2cc** [CyFeng16/MVIMP#24]
Well, when I wanted to add waifu2x to the list of models, there were no linux binaries for waifu2x-ncnn-vulkan, but almost as if the developer was watching us, I release linux binaries.
I tested it in Colab, and it works... I do not think we should delete it from the list, but maybe we should consider just downloading it directly, the only thing that needs to be installed separately is the Vulkan sdk.

Instalation of VulkanSDK:
`wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.135-bionic.list http://packages.lunarg.com/vulkan/1.2.135/lunarg-vulkan-1.2.135-bionic.list
sudo apt update
sudo apt install vulkan-sdk`

Latest version of linux [here](https://github.com/nihui/waifu2x-ncnn-vulkan/releases/download/20200530/waifu2x-ncnn-vulkan-20200530-linux.zip).

... This is sad.

**Comment by CyFeng16** [comment]
In my respect, it is not a big deal. Either we download to install or install from a package manager, we do install the Vulkan SDK. Therefore, in preparation stage which we don't want users to be bothered, it may be equal. What do you think?

**Comment by re2cc** [comment]
I thought the same, I mentioned it because maybe for someone the compilation could be slow or give problems... I will leave it up to you, I just wanted to mention it

**Comment by CyFeng16** [comment]
You are welcome!
Subjectively, I divided all optimizations into three types according to the frequency of use:
1. Functions used in construction;
2. Functions used once in the runtime;
3. Functions used in the runtime cycle;

I do not tend to spend time optimizing for 1 and 2. 
3 is the most influential part of the user experience and needs to be improved as much as possible.
Of course, this is just a personal point of view, and any possible (non-destructive) improvements are welcome in the open-source field.
