### ISSUE TITLE
Need feedback for test branch

### ISSUE THREAD

**Issue by CyFeng16** [CyFeng16/MVIMP#26]
Suggestion:
Make it so we can DAIN interpolate multiple videos in a row.
Example: Have multiple videos in the input folder, and DAIN interpolate them all 1 by 1 automatically.

*I have tried doing this, but I'm not a python expert, and I'm still struggling to change whats needed for this to work.

This is good for when we have large videos, we split them into parts first, so when using COLAB, even if we hit the 12h session limit, we don't lose the entire progress.

Also good for when we split the video into different scenes using scene change detection beforehand. (Still trying to implement auto scene detection into the repo, for now I'm using "PySceneDetect" on my local computer to split the video into the different scenes first.)

_Originally posted by @BrokenSilence in https://github.com/CyFeng16/MVIMP/issues/2#issuecomment-635919298_

**Comment by CyFeng16** [comment]
Hi, @BrokenSilence .
I have done something following your suggestion, however, I have no time to check if it really works.
Would you use DAIN with my new branch `cyfeng-0531-strict-IO-check`, use `!git clone -b cyfeng-0531-strict-IO-check https://github.com/CyFeng16/MVIMP.git` instead of `!git clone https://github.com/CyFeng16/MVIMP.git`. Have a try and tell me whether everything is OK.

**Comment by Zotikus1001** [comment]
After finishing interpolating the first video, I get this:
```
100% 21/21 [02:01<00:00,  5.79s/it]
Traceback (most recent call last):
  File "inference_dain.py", line 80, in <module>
    output_video_file = f"{args.input_video.split('.')[0]}-{target_fps}.{args.input_video.split('.')[1]}"
AttributeError: 'Namespace' object has no attribute 'input_video'
```

**Comment by CyFeng16** [comment]
Many thanks. I know what's wrong.
