### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by Rishi5583** [CyFeng16/MVIMP#30]
When running code from from cmd prompt in python 3.6.8
:
python inference_dain.py -input test.mp4
Possible to make the dll file 
for this issue:
import filterinterpolation_cuda as my_lib

**Comment by CyFeng16** [comment]
incomplete preparation cause it.  check the info and make sure all modules
are ready.

Rishi5583 <notifications@github.com> 于 2020年8月10日周一 上午12:08写道：
