### ISSUE TITLE
Is waifu2x the right choice?

### ISSUE THREAD

**Issue by re2cc** [CyFeng16/MVIMP#6]
Hi, I know, I am the one who suggested waifu2x, but I have been doing some research and came across some projects based on waifu2x.
Essentially they look the same, but the speed and ease of installation is greater.
I think the best option would be [Dandere2x](https://github.com/aka-katto/dandere2x). It is a tool which gathers multiple "editions" of waifu2x, besides that, it has the possibility to do it directly in videos, it seems to be quite fast. Honestly I do not understand if there is a way to run it in terminal directly, but I do not think it is difficult to transform it to work in terminal.
I was unable to compile it, the binaries that there are, are completely designed for Windows, has a guide to compile in linux, but the truth is that I could not run it, or my English and knowledge of linux are horrible, or the documentation is not understood. The most I got to compile, was [waifu2x-ncnn-vulkan](https://github.com/nihui/waifu2x-ncnn-vulkan), but [my notebook](https://drive.google.com/open?id=1xxLQofw_pK-zAsU3NUcJCuopEzNmgbDw), was not able to run it at the end, I get an error.
I am sorry to have mentioned this so late, but I found it very recently, I hope you can raise it or tell me if there is something wrong with what I say.
**Thanks.**

**Comment by CyFeng16** [comment]
From a license perspective, both `waifu2x`(MIT) and `Dandere2x`(GPLv3) licenses give us permission to change. Cheers.
`Dandere2x` pursues faster speed, and `waifu2x` brings higher quality, and I subjectively prefer high quality. Therefore, `waifu2x` and `Video2x` may be more in line with our possible user group.
BUT, who knows XD

**Comment by re2cc** [comment]
It's a good point, video2x also has better documentation, it's not putting the code in and running it, but it seems to be better documented and instructed.
Well, anything is good.

**Comment by re2cc** [comment]
> From a license perspective, both `waifu2x`(MIT) and `Dandere2x`(GPLv3) licenses give us permission to change. Cheers.
> `Dandere2x` pursues faster speed, and `waifu2x` brings higher quality, and I subjectively prefer high quality. Therefore, `waifu2x` and `Video2x` may be more in line with our possible user group.
> BUT, who knows XD

When you talked about Video2x, I was interested, I tried to run it in Colab, without success, but I managed to run [waifu2x-caffe](https://github.com/lltcggie/waifu2x-caffe).
The bad thing is that Colab is very centered in Colab, so I am sure, it would mot work in Windows, and maybe not in local linux either. I would have liked to make it more "universal", but waifu2x-caffe is very focused on windows, you have to compile cmake (I think), caffe and waifu2x-caffe itself to work; I had to edit some files to make it work.
In case you added Video2x or waifu2x-caffe itself at some point, I could help you with the execution. Do you think you can use the notebook?

**Comment by CyFeng16** [comment]
Yes, many super-resolution programs only (choose to) perform well on windows platforms. Thanks for reminding me.

**Comment by re2cc** [comment]
Ok, I think that the part of ask for gpu and some parts maybe are useless, but it works.
[https://colab.research.google.com/drive/1fncV5THJ_utaSq6fUwrCkj9_tjjCaM3H?usp=sharing](
https://colab.research.google.com/drive/1fncV5THJ_utaSq6fUwrCkj9_tjjCaM3H?usp=sharing)

**Comment by CyFeng16** [comment]
I glanced briefly. It seems that your attempt at this time was very tortuous, and I even saw the hard coding from Pastebin. XD
Advanced DAIN WIP and more caffeine are needed, however, I will try it later!

**Comment by re2cc** [comment]
xD, I'm trying to reduce the size and complexity, but I don't know how much I can do... For some reason, each graph has to change some options and I don't know how to generalize it.

**Comment by CyFeng16** [comment]
@EtianAM Maybe we can close this issue since we have added waifu2x-nccn-vulkan.

**Comment by re2cc** [comment]
> @EtianAM Maybe we can close this issue since we have added waifu2x-nccn-vulkan.

Okay, I forgot xD
